# Generated by Django 4.2.3 on 2023-07-13 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_ticket_created_at_ticket_has_response'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFollows',
        ),
    ]
