# Generated by Django 4.0.4 on 2023-07-13 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_alter_review_user_alter_ticket_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='created_at',
            new_name='time_created',
        ),
    ]
