# Generated by Django 4.2.3 on 2023-07-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_follows',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='authentication.user'),
        ),
    ]
